sublimelsp/repository

- .github/workflows/on-pull-request.yml
Add "review_requested" to other types that are enabled by default
> trigger bot when review is requested

- repository.json
Moved from https://github.com/wbond/package_control_channel/pull/8035
> Add LSP-Dart

- repository.json
Compare with https://packagecontrol.io/packages/Tabnine
> Apply search engine optimization

- repository.json
Moved from https://github.com/wbond/package_control_channel/pull/8027
> Add LSP-SourceKit

- repository.json
Language Server providing spelling and grammar correction, supporting LaTex and Markdown.
> Add LSP-ltex-ls

- repository.json
Packaging server files in the package was a mistake.
> Add LSP-lua

- repository.json
> enable linux platform for LSP-SourceKit

- repository.json
close https://github.com/sublimelsp/LSP/issues/1621
> Add LSP-Bicep

- repository.json
Hello.
Leo is a functional, statically-typed programming language built for writing private applications.
https://leo-lang.org/
https://developer.aleo.org/developer/getting_started/overview
This package provides LSP features (diagnostics, completions, hovers, go-to definitions, semantic highlights) and also a theme for syntax token coloring.
> Add LSP-leo package.

- repository.json
> Add rust-analyzer

- repository.json
> format / sort plugin by name

- repository.json
@TheSecEng mind this?
Eventaully, it will looks like this on PC website.
> Add @jfcherng as LSP-copilot author as well

- repository.json
Also switched to repo in sublimelsp.
> LSP-serenate is ST3-only

- auto-update-repository.py
- repository.json
LSP-biome is a continuation of LSP-rome which shall be forgotten.
See https://github.com/rome/tools readme.
> Add LSP-biome

- repository.json
> Pin LSP-elixir for ST3

- repository.json
> Pin LSP-bash for ST3

- repository.json
> Pin LSP-ruff for ST3

- repository.json
> Pin LSP-stylelint for ST3

- repository.json
> Pin LSP-pylsp for ST3

- repository.json
> Pin LSP-angular for ST3

- repository.json
> Pin LSP-svelte for ST3

- repository.json
> Pin LSP-intelephense for ST3

- repository.json
> Pin LSP-graphql for ST3

- repository.json
> Pin LSP-vue for ST3

- repository.json
> Pin LSP-tailwindcss for ST3

- repository.json
Reverts sublimelsp/repository#120
> Revert "Add LSP-some-sass"
