- .github/workflows/on-new-release.yml
- auto-update-repository.py
Another repo in this organization can do a rest api request when it publishes a new release. At least, that's the plan. It works at least locally somewhat. But I don't know how to test the workflow locally.
> Create pull requests automatically when another repo requests it via the REST api

- review_bot/run_repo_tests.py
There are some small bits of functionality that are included in
packagecontrol.io repo but not upstreamed.
> Fix review-bot to work with pypi version of st_package_reviewer

- repository.json
With latest LSP3 release we'll be able to use the same branch for both
ST3 and ST4. Both dotted settings and parsing variables are supported.
https://github.com/sublimelsp/LSP-pyright/pull/19
> Remove "st3" release branch for LSP-pyright

- repository.json
[Volar]: https://github.com/johnsoncodehk/volar
[Volar] is a language support plugin built specifically for Vue 3.
[LSP-Volar](https://github.com/sublimelsp/LSP-volar) integrates the [Volar] language server with SublimeLSP, providing autocompletion, linting, and typechecking of Vue 3 components.
> Add LSP-Volar

- repository.json
After https://github.com/scalameta/metals-sublime/pull/57 LSP-metals will be ST4 only
I created a last tag for ST3 https://github.com/scalameta/metals-sublime/releases/tag/st3-v0.9.0
> Update default tag for LSP-metals

- repository.json
This PR adds `LSP-prisma` (https://github.com/Sublime-Instincts/LSP-prisma)
`LSP-prisma` is a LSP helper package that uses the `Prisma Language Tools` to provide LSP support for Prisma schema files.
> Add `LSP-prisma`.

- repository.json
LSP-Grammarly is a small helper package that downloads and interfaces with the [Grammarly language server](https://github.com/znck/grammarly) to get [Grammarly](https://grammarly.com/)'s typing assistance in sublime.
> Add LSP-Grammarly

- repository.json
We are adding support for the Aleo language https://developer.aleo.org/aleo/overview/. 
The Leo and Aleo languages are used to create programs in the Aleo network.
LSP for both of them is needed to create a program.
To allow users to work with both languages by installing one package we want to change the name of the repository and the description of this package.
Previous PR for LSP-leo https://github.com/sublimelsp/repository/pull/51
> Rename repository from LSP-leo to LSP-aleo-developer

- repository.json
We need to change the name of the package and the repository name once again.
Previous PR for LSP-aleo-developer https://github.com/sublimelsp/repository/pull/68
> Rename repository LSP-aleo-developer to LSP-leo

- repository.json
@rchl 
- I've tagged both `1.2.19` and `st3-1.2.19` on https://github.com/sublimelsp/LSP-pyright/releases. `1.2.20` is planned to be ST4-only.
- I've created `st3` branch as a record. The `master` branch will be for ST 4.
- We drop ST3 support because the inherited default Python syntax is now `version:2` as of ST 4148. `version:2` syntax is a new feature of ST 4. Related PR: https://github.com/sublimelsp/LSP-pyright/pull/224
> LSP-pyright is ST4-only in newer releases

- repository.json
My package adds a VHDL LSP server to Sublime Text. It just adds a native way to install and use [rust_hdl](https://github.com/VHDL-LS/rust_hdl).
> Add LSP-VHDL-ls

- repository.json
It doesn't make sense to allow installing helper packages on ST3092 if LSP is requires at least ST3154.
Hence this commit restricts all helpers to LSP's least ST build.
> Restrict LSP-... helper packages to LSP's least ST build

- repository.json
lsp_utils 2.x is last compatible ST3 release
As of 3.0.0 ST4070+ is requied.
This PR makes required changes for Package control to pick up correct versions.
> Separate lsp_utils releases for ST3/4

- repository.json
They have been not working for ST 3 for quite a while actually...
https://github.com/sublimelsp/LSP-css/issues/46
https://github.com/sublimelsp/LSP-html/issues/45
By the way, LSP-json is reported too. https://github.com/sublimelsp/LSP-css/issues/46#issuecomment-1826738397
---
I have created `st3` branch and release tag for LSP-css/html, so this PR should be safe to merge.
> Separate LSP-css/html releases for ST3/4

- repository.json
The latest LSP-yaml still works on ST 3 but I don't think devs want to test it for ST 3 for every future release and we may forget to test. So, let's just leave it alone.
> Separate LSP-yaml releases for ST3/4

- repository.json
https://github.com/sublimelsp/LSP-basedpyright
> Add LSP-basedpyright

- repository.json
https://github.com/sublimelsp/LSP-nimlangserver
> Add LSP-nimlangserver

- repository.json
This is a language client wrapper around the [pyvoice-language-server pypi package](https://pypi.org/project/pyvoice-language-server/)
and acts as editor portion of the [pyvoice](https://github.com/PythonVoiceCodingPlugin) for sublime text. Quoting from  the organization's home page
> pyvoice is an experimental project that is aimed at developers that are writing python code using their voice instead of/alongside with a traditional keyboard. It attempts to provide them with specialized IDE features tailored at their use case, more specifically, it tries to
> 
> - primarily improve the dictation accuracy for coding tasks  by extracting information from the user's codebase via static analysis and utilizing it as context for the speech recognition engine
> 
> - secondarily allow for …
> Add LSP-pyvoice

- repository.json
LSP-vetur is a mirror of no longer maintained LSP-vue.
I have plans to make LSP-vue into the main/official language server based on Vue language features 2.x (LSP-volar is based on Vue language features 1.x which is not compatible with 2.x).
It's a bit of a non-standard approach and it will break flow for users of LSP-vue but:
a) LSP-vue was always badly named for what it was (should have been LSP-vetur from the start)
b) Vetur is no longer maintained and it makes it look bad to make it look like this is the official server for Vue.
> add LSP-vetur

- repository.json
https://github.com/niksy/LSP-sass
> Add LSP-some-sass

- repository.json
https://github.com/niksy/LSP-twiggy
Same as https://github.com/sublimelsp/repository/pull/120, we can switch respository to Sublime LSP organization.
> Add LSP-twiggy

- repository.json
Should fix https://github.com/sublimelsp/LSP/issues/2588
ST build 4132 was released almost three years ago, so I guess it's okay to drop support for installing LSP on even older ST4 builds.
> Update minimum ST version required to install LSP

- repository.json
If you visit https://packages.sublimetext.io/?q=lsp&sort=installed
You will notice that LSP has a lot of labels.
There was some discussion on Discord to reduce the number of tags on LSP,
and to add a `lsp` label for LSP-* packages.
I did agree with this, so thus I created this PR.
> Reduce the number of labels

- repository.json
LSP helper for `ty` - an extremely fast Python type checker, written in Rust.
https://github.com/sublimelsp/LSP-ty
> Add LSP-ty
